{
 "title": "Grafana Agent Operational",
 "tags": [ "grafana-agent-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(agent_build_info, job)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(agent_build_info{job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Garbage Collection Seconds",
   "type": "timeseries",
   "description": "A summary of the pause duration of garbage collection cycles.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_count{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Go Heap",
   "type": "timeseries",
   "description": "Number of heap bytes that are in use.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Go Routines",
   "type": "timeseries",
   "description": "Number of goroutines that currently exist.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Total user and system CPU time spent in seconds.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "TCP Connections",
   "type": "timeseries",
   "description": "Number of accepted TCP connections.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "agent_tcp_connections{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Prometheus Read",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Bytes/Series/Instance",
   "type": "timeseries",
   "description": "Average bytes over number of active series being tracked by the WAL storage grouped by instance.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\n            (sum by (instance) (avg_over_time(go_memstats_heap_inuse_bytes{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])))\n            /\n            (sum by (instance) (agent_wal_storage_active_series{job=~\"$job\", instance=~\"$instance\"}))\n          ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes/Series/Job",
   "type": "timeseries",
   "description": "Average bytes over number of active series being tracked by the WAL storage by Job.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\n            (sum by (job) (avg_over_time(go_memstats_heap_inuse_bytes{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])))\n            /\n            (sum by (job) (agent_wal_storage_active_series{job=~\"$job\", instance=~\"$instance\"}))\n          ",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Series/Instance",
   "type": "timeseries",
   "description": "Number of active series being tracked by the WAL storage grouped by instance.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (agent_wal_storage_active_series{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Series/Config/Instance",
   "type": "timeseries",
   "description": "Number of active series being tracked by the WAL storage grouped by instance.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (agent_wal_storage_active_series{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Series/Config/Job",
   "type": "timeseries",
   "description": "Number of active series being tracked by the WAL storage grouped by job.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (agent_wal_storage_active_series{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}